
// Objective-C API for talking to the following Go packages
//
//	mykeysdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mykeycore_FRAMEWORK_H__
#define __Mykeycore_FRAMEWORK_H__

#include "Mykeycore.objc.h"
#include "universe.objc.h"

#endif
