#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import Mykeycore;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MYKEYWalletLib",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC14MYKEYWalletLib19BaseProtocolRequest")
@interface BaseProtocolRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull appKey;
@property (nonatomic, copy) NSString * _Nonnull protocol;
@property (nonatomic, copy) NSString * _Nonnull version;
@property (nonatomic, copy) NSString * _Nonnull dappName;
@property (nonatomic, copy) NSString * _Nonnull dappIcon;
@property (nonatomic, copy) NSString * _Nonnull action;
@property (nonatomic, copy) NSString * _Nonnull uuID;
@property (nonatomic, copy) NSString * _Nonnull callback;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib24AuthorizeProtocolRequest")
@interface AuthorizeProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSString * _Nonnull loginUrl;
@property (nonatomic, copy) NSString * _Nonnull loginMemo;
@property (nonatomic, copy) NSString * _Nonnull dappUserName;
@property (nonatomic, copy) NSString * _Nonnull requestPubKey;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11BaseRequest")
@interface BaseRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull callbackUrl;
@property (nonatomic, copy) NSString * _Nonnull info;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib16AuthorizeRequest")
@interface AuthorizeRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull userName;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib10BaseAction")
@interface BaseAction : NSObject
@property (nonatomic, copy) NSString * _Nonnull info;
@property (nonatomic, copy) NSString * _Nonnull account;
@property (nonatomic, copy) NSString * _Nonnull name;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15BaseJniResponse")
@interface BaseJniResponse : NSObject
@property (nonatomic) NSInteger result_code;
@property (nonatomic, copy) NSString * _Nonnull result_message;
@property (nonatomic) id _Nullable result_data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC14MYKEYWalletLib14ContractAction")
@interface ContractAction : BaseAction
/// JSONString
@property (nonatomic, copy) NSString * _Nonnull data;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib23ContractProtocolRequest")
@interface ContractProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSArray<BaseAction *> * _Nonnull actions;
@property (nonatomic, copy) NSString * _Nonnull desc;
@property (nonatomic, copy) NSString * _Nonnull contractUrl;
@property (nonatomic, copy) NSString * _Nonnull orderId;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15ContractRequest")
@interface ContractRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic, copy) NSArray<BaseAction *> * _Nonnull actions;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib13EmptyResponse")
@interface EmptyResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib19EncodeParamResponse")
@interface EncodeParamResponse : NSObject
@property (nonatomic, copy) NSString * _Nonnull encode_data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ErrorCode, closed) {
/// 0
  ErrorCodeCancel = 0,
/// 1
  ErrorCodeSuccess = 1,
/// 2
  ErrorCodeFailure = 2,
/// 10001
  ErrorCodeCannotWakeUp = 10001,
/// 10002
  ErrorCodeNotInstall = 10002,
/// 10003
  ErrorCodeFreezed = 10003,
/// 10004
  ErrorCodeUninitialized = 10004,
/// 10005
  ErrorCodeTimeOut = 10005,
/// 10006
  ErrorCodeDuplicateBound = 10006,
/// 10007
  ErrorCodeUnbound = 10007,
/// 10008
  ErrorCodeDappBounded = 10008,
/// 10009
  ErrorCodeMYKEYBounded = 10009,
/// 10010
  ErrorCodeBoundInfoMismatch = 10010,
/// 10011
  ErrorCodeMYKEYAccountNotExist = 10011,
/// 10012
  ErrorCodeIllegalParameter = 10012,
/// 10013
  ErrorCodeInsufficientBalance = 10013,
};

@class InitRequest;
@class InitSimpleRequest;

SWIFT_CLASS("_TtC14MYKEYWalletLib10InitHandle")
@interface InitHandle : NSObject
/// Initialization needs to be performed on the main thread.
- (InitRequest * _Nonnull)handleWithInitRequest:(InitRequest * _Nonnull)initRequest SWIFT_WARN_UNUSED_RESULT;
- (InitRequest * _Nonnull)handleWithInitSimpleRequest:(InitSimpleRequest * _Nonnull)initSimpleRequest SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11InitRequest")
@interface InitRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull protocol;
@property (nonatomic, copy) NSString * _Nonnull appKey;
@property (nonatomic, copy) NSUUID * _Nullable UUID;
@property (nonatomic, copy) NSString * _Nonnull dappName;
@property (nonatomic, copy) NSString * _Nonnull dappIcon;
/// Default is ‘false’ , If MYKEY is not installed, go to the download page.
@property (nonatomic) BOOL disableInstall;
/// scheme
@property (nonatomic, copy) NSString * _Nonnull scheme;
/// Base url of MYKEY server,default is the distribution environment.
@property (nonatomic, copy) NSString * _Nonnull mykeyServer;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithInitSimpleRequest:(InitSimpleRequest * _Nonnull)initSimpleRequest OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib17InitSimpleRequest")
@interface InitSimpleRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull protocol;
@property (nonatomic, copy) NSString * _Nonnull dappName;
@property (nonatomic, copy) NSString * _Nonnull dappIcon;
/// Default is ‘false’ , If MYKEY is not installed, go to the download page.
@property (nonatomic) BOOL disableInstall;
/// scheme
@property (nonatomic, copy) NSString * _Nonnull scheme;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib19JniUserAgentRequest")
@interface JniUserAgentRequest : NSObject
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib16MYKEYApiResponse")
@interface MYKEYApiResponse : NSObject <MykeycoreApiRequestCallback>
- (nonnull instancetype)initWithSuccess:(void (^ _Nullable)(NSString * _Nonnull))success failure:(void (^ _Nullable)(NSString * _Nonnull))failure OBJC_DESIGNATED_INITIALIZER;
- (void)onSuccess:(NSString * _Null_unspecified)response;
- (void)onError:(NSInteger)errorCode errorMsg:(NSString * _Null_unspecified)errorMsg;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib13MYKEYResponse")
@interface MYKEYResponse : NSObject
@property (nonatomic, copy) void (^ _Nullable onSuccess)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onFailure)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onCancel)(void);
- (nonnull instancetype)initWithSuccess:(void (^ _Nullable)(NSString * _Nonnull))success failure:(void (^ _Nullable)(NSString * _Nonnull))failure cancelled:(void (^ _Nullable)(void))cancelled OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11MYKEYWallet")
@interface MYKEYWallet : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MYKEYWallet * _Nonnull shared;)
+ (MYKEYWallet * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull appKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull scheme;
@property (nonatomic, readonly, copy) NSString * _Nonnull uuid;
@property (nonatomic, readonly, copy) NSString * _Nonnull dappName;
@property (nonatomic, readonly, copy) NSString * _Nonnull dappIcon;
@property (nonatomic, readonly) BOOL disableInstall;
@property (nonatomic, readonly, copy) NSString * _Nonnull protocol;
@property (nonatomic, readonly, copy) NSString * _Nonnull mykeyServer;
@end


@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
/// Initialization needs to be performed on the main thread.
- (void)initWalletWithInitData:(InitRequest * _Nonnull)initData SWIFT_METHOD_FAMILY(none);
/// Initialization needs to be performed on the main thread.
- (void)initWalletSimpleWithInitSimpleData:(InitSimpleRequest * _Nonnull)initSimpleData SWIFT_METHOD_FAMILY(none);
@end


@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
- (void)getBalanceWithChain:(NSString * _Nonnull)chain code:(NSString * _Nonnull)code symbol:(NSString * _Nonnull)symbol completionHandler:(MYKEYApiResponse * _Nonnull)completionHandler;
- (void)getUnlockListWithChain:(NSString * _Nonnull)chain code:(NSString * _Nonnull)code symbol:(NSString * _Nonnull)symbol completionHandler:(MYKEYApiResponse * _Nonnull)completionHandler;
- (void)getBoundInfoWithCompletionHandler:(MYKEYApiResponse * _Nonnull)completionHandler;
@end


@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
/// Parse the callback data
- (void)handleUrlWithUrl:(NSURL * _Nonnull)url;
@end

@class TransferRequest;
@class SignRequest;

@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
- (void)authorizeWithAuthorizeRequest:(AuthorizeRequest * _Nonnull)authorizeRequest response:(MYKEYResponse * _Nonnull)response;
- (void)transferWithTransferRequest:(TransferRequest * _Nonnull)transferRequest response:(MYKEYResponse * _Nonnull)response;
- (void)contractWithContractRequest:(ContractRequest * _Nonnull)contractRequest response:(MYKEYResponse * _Nonnull)response;
- (void)signWithSignRequest:(SignRequest * _Nonnull)signRequest response:(MYKEYResponse * _Nonnull)response;
- (void)redirectToMYKEYWithSimpleWalletWithBaseRequest:(BaseProtocolRequest * _Nonnull)baseRequest response:(MYKEYResponse * _Nonnull)response;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15MYKEYWalletResp")
@interface MYKEYWalletResp : NSObject
@property (nonatomic, copy) NSString * _Nonnull action;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull data;
@property (nonatomic) NSInteger code;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib21RequestPubKeyResponse")
@interface RequestPubKeyResponse : NSObject
@property (nonatomic, copy) NSString * _Nonnull pub_key;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib19SignProtocolRequest")
@interface SignProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, copy) NSString * _Nonnull signUrl;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11SignRequest")
@interface SignRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TransferData;

SWIFT_CLASS("_TtC14MYKEYWalletLib14TransferAction")
@interface TransferAction : BaseAction
@property (nonatomic, strong) TransferData * _Nonnull data;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib12TransferData")
@interface TransferData : NSObject
@property (nonatomic, copy) NSString * _Nonnull from;
@property (nonatomic, copy) NSString * _Nonnull to;
@property (nonatomic, copy) NSString * _Nonnull quantity;
@property (nonatomic, copy) NSString * _Nonnull memo;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib23TransferProtocolRequest")
@interface TransferProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSString * _Nonnull from;
@property (nonatomic, copy) NSString * _Nonnull to;
@property (nonatomic) double amount;
@property (nonatomic, copy) NSString * _Nonnull contract;
@property (nonatomic, copy) NSString * _Nonnull symbol;
@property (nonatomic) NSInteger precision;
@property (nonatomic, copy) NSString * _Nonnull dappData;
@property (nonatomic, copy) NSString * _Nonnull desc;
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic, copy) NSString * _Nonnull transferUrl;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15TransferRequest")
@interface TransferRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull from;
@property (nonatomic, copy) NSString * _Nonnull to;
@property (nonatomic, copy) NSString * _Nonnull contractName;
@property (nonatomic, copy) NSString * _Nonnull memo;
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic) double amount;
@property (nonatomic, copy) NSString * _Nonnull symbol;
@property (nonatomic) NSInteger decimal;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end







#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import Mykeycore;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MYKEYWalletLib",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC14MYKEYWalletLib19BaseProtocolRequest")
@interface BaseProtocolRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull appKey;
@property (nonatomic, copy) NSString * _Nonnull protocol;
@property (nonatomic, copy) NSString * _Nonnull version;
@property (nonatomic, copy) NSString * _Nonnull dappName;
@property (nonatomic, copy) NSString * _Nonnull dappIcon;
@property (nonatomic, copy) NSString * _Nonnull action;
@property (nonatomic, copy) NSString * _Nonnull uuID;
@property (nonatomic, copy) NSString * _Nonnull callback;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib24AuthorizeProtocolRequest")
@interface AuthorizeProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSString * _Nonnull loginUrl;
@property (nonatomic, copy) NSString * _Nonnull loginMemo;
@property (nonatomic, copy) NSString * _Nonnull dappUserName;
@property (nonatomic, copy) NSString * _Nonnull requestPubKey;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11BaseRequest")
@interface BaseRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull callbackUrl;
@property (nonatomic, copy) NSString * _Nonnull info;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib16AuthorizeRequest")
@interface AuthorizeRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull userName;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib10BaseAction")
@interface BaseAction : NSObject
@property (nonatomic, copy) NSString * _Nonnull info;
@property (nonatomic, copy) NSString * _Nonnull account;
@property (nonatomic, copy) NSString * _Nonnull name;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15BaseJniResponse")
@interface BaseJniResponse : NSObject
@property (nonatomic) NSInteger result_code;
@property (nonatomic, copy) NSString * _Nonnull result_message;
@property (nonatomic) id _Nullable result_data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC14MYKEYWalletLib14ContractAction")
@interface ContractAction : BaseAction
/// JSONString
@property (nonatomic, copy) NSString * _Nonnull data;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib23ContractProtocolRequest")
@interface ContractProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSArray<BaseAction *> * _Nonnull actions;
@property (nonatomic, copy) NSString * _Nonnull desc;
@property (nonatomic, copy) NSString * _Nonnull contractUrl;
@property (nonatomic, copy) NSString * _Nonnull orderId;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15ContractRequest")
@interface ContractRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic, copy) NSArray<BaseAction *> * _Nonnull actions;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib13EmptyResponse")
@interface EmptyResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib19EncodeParamResponse")
@interface EncodeParamResponse : NSObject
@property (nonatomic, copy) NSString * _Nonnull encode_data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ErrorCode, closed) {
/// 0
  ErrorCodeCancel = 0,
/// 1
  ErrorCodeSuccess = 1,
/// 2
  ErrorCodeFailure = 2,
/// 10001
  ErrorCodeCannotWakeUp = 10001,
/// 10002
  ErrorCodeNotInstall = 10002,
/// 10003
  ErrorCodeFreezed = 10003,
/// 10004
  ErrorCodeUninitialized = 10004,
/// 10005
  ErrorCodeTimeOut = 10005,
/// 10006
  ErrorCodeDuplicateBound = 10006,
/// 10007
  ErrorCodeUnbound = 10007,
/// 10008
  ErrorCodeDappBounded = 10008,
/// 10009
  ErrorCodeMYKEYBounded = 10009,
/// 10010
  ErrorCodeBoundInfoMismatch = 10010,
/// 10011
  ErrorCodeMYKEYAccountNotExist = 10011,
/// 10012
  ErrorCodeIllegalParameter = 10012,
/// 10013
  ErrorCodeInsufficientBalance = 10013,
};

@class InitRequest;
@class InitSimpleRequest;

SWIFT_CLASS("_TtC14MYKEYWalletLib10InitHandle")
@interface InitHandle : NSObject
/// Initialization needs to be performed on the main thread.
- (InitRequest * _Nonnull)handleWithInitRequest:(InitRequest * _Nonnull)initRequest SWIFT_WARN_UNUSED_RESULT;
- (InitRequest * _Nonnull)handleWithInitSimpleRequest:(InitSimpleRequest * _Nonnull)initSimpleRequest SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11InitRequest")
@interface InitRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull protocol;
@property (nonatomic, copy) NSString * _Nonnull appKey;
@property (nonatomic, copy) NSUUID * _Nullable UUID;
@property (nonatomic, copy) NSString * _Nonnull dappName;
@property (nonatomic, copy) NSString * _Nonnull dappIcon;
/// Default is ‘false’ , If MYKEY is not installed, go to the download page.
@property (nonatomic) BOOL disableInstall;
/// scheme
@property (nonatomic, copy) NSString * _Nonnull scheme;
/// Base url of MYKEY server,default is the distribution environment.
@property (nonatomic, copy) NSString * _Nonnull mykeyServer;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithInitSimpleRequest:(InitSimpleRequest * _Nonnull)initSimpleRequest OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib17InitSimpleRequest")
@interface InitSimpleRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull protocol;
@property (nonatomic, copy) NSString * _Nonnull dappName;
@property (nonatomic, copy) NSString * _Nonnull dappIcon;
/// Default is ‘false’ , If MYKEY is not installed, go to the download page.
@property (nonatomic) BOOL disableInstall;
/// scheme
@property (nonatomic, copy) NSString * _Nonnull scheme;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib19JniUserAgentRequest")
@interface JniUserAgentRequest : NSObject
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib16MYKEYApiResponse")
@interface MYKEYApiResponse : NSObject <MykeycoreApiRequestCallback>
- (nonnull instancetype)initWithSuccess:(void (^ _Nullable)(NSString * _Nonnull))success failure:(void (^ _Nullable)(NSString * _Nonnull))failure OBJC_DESIGNATED_INITIALIZER;
- (void)onSuccess:(NSString * _Null_unspecified)response;
- (void)onError:(NSInteger)errorCode errorMsg:(NSString * _Null_unspecified)errorMsg;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib13MYKEYResponse")
@interface MYKEYResponse : NSObject
@property (nonatomic, copy) void (^ _Nullable onSuccess)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onFailure)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onCancel)(void);
- (nonnull instancetype)initWithSuccess:(void (^ _Nullable)(NSString * _Nonnull))success failure:(void (^ _Nullable)(NSString * _Nonnull))failure cancelled:(void (^ _Nullable)(void))cancelled OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11MYKEYWallet")
@interface MYKEYWallet : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MYKEYWallet * _Nonnull shared;)
+ (MYKEYWallet * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull appKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull scheme;
@property (nonatomic, readonly, copy) NSString * _Nonnull uuid;
@property (nonatomic, readonly, copy) NSString * _Nonnull dappName;
@property (nonatomic, readonly, copy) NSString * _Nonnull dappIcon;
@property (nonatomic, readonly) BOOL disableInstall;
@property (nonatomic, readonly, copy) NSString * _Nonnull protocol;
@property (nonatomic, readonly, copy) NSString * _Nonnull mykeyServer;
@end


@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
/// Initialization needs to be performed on the main thread.
- (void)initWalletWithInitData:(InitRequest * _Nonnull)initData SWIFT_METHOD_FAMILY(none);
/// Initialization needs to be performed on the main thread.
- (void)initWalletSimpleWithInitSimpleData:(InitSimpleRequest * _Nonnull)initSimpleData SWIFT_METHOD_FAMILY(none);
@end


@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
- (void)getBalanceWithChain:(NSString * _Nonnull)chain code:(NSString * _Nonnull)code symbol:(NSString * _Nonnull)symbol completionHandler:(MYKEYApiResponse * _Nonnull)completionHandler;
- (void)getUnlockListWithChain:(NSString * _Nonnull)chain code:(NSString * _Nonnull)code symbol:(NSString * _Nonnull)symbol completionHandler:(MYKEYApiResponse * _Nonnull)completionHandler;
- (void)getBoundInfoWithCompletionHandler:(MYKEYApiResponse * _Nonnull)completionHandler;
@end


@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
/// Parse the callback data
- (void)handleUrlWithUrl:(NSURL * _Nonnull)url;
@end

@class TransferRequest;
@class SignRequest;

@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
- (void)authorizeWithAuthorizeRequest:(AuthorizeRequest * _Nonnull)authorizeRequest response:(MYKEYResponse * _Nonnull)response;
- (void)transferWithTransferRequest:(TransferRequest * _Nonnull)transferRequest response:(MYKEYResponse * _Nonnull)response;
- (void)contractWithContractRequest:(ContractRequest * _Nonnull)contractRequest response:(MYKEYResponse * _Nonnull)response;
- (void)signWithSignRequest:(SignRequest * _Nonnull)signRequest response:(MYKEYResponse * _Nonnull)response;
- (void)redirectToMYKEYWithSimpleWalletWithBaseRequest:(BaseProtocolRequest * _Nonnull)baseRequest response:(MYKEYResponse * _Nonnull)response;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15MYKEYWalletResp")
@interface MYKEYWalletResp : NSObject
@property (nonatomic, copy) NSString * _Nonnull action;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull data;
@property (nonatomic) NSInteger code;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib21RequestPubKeyResponse")
@interface RequestPubKeyResponse : NSObject
@property (nonatomic, copy) NSString * _Nonnull pub_key;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib19SignProtocolRequest")
@interface SignProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, copy) NSString * _Nonnull signUrl;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11SignRequest")
@interface SignRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TransferData;

SWIFT_CLASS("_TtC14MYKEYWalletLib14TransferAction")
@interface TransferAction : BaseAction
@property (nonatomic, strong) TransferData * _Nonnull data;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib12TransferData")
@interface TransferData : NSObject
@property (nonatomic, copy) NSString * _Nonnull from;
@property (nonatomic, copy) NSString * _Nonnull to;
@property (nonatomic, copy) NSString * _Nonnull quantity;
@property (nonatomic, copy) NSString * _Nonnull memo;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib23TransferProtocolRequest")
@interface TransferProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSString * _Nonnull from;
@property (nonatomic, copy) NSString * _Nonnull to;
@property (nonatomic) double amount;
@property (nonatomic, copy) NSString * _Nonnull contract;
@property (nonatomic, copy) NSString * _Nonnull symbol;
@property (nonatomic) NSInteger precision;
@property (nonatomic, copy) NSString * _Nonnull dappData;
@property (nonatomic, copy) NSString * _Nonnull desc;
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic, copy) NSString * _Nonnull transferUrl;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15TransferRequest")
@interface TransferRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull from;
@property (nonatomic, copy) NSString * _Nonnull to;
@property (nonatomic, copy) NSString * _Nonnull contractName;
@property (nonatomic, copy) NSString * _Nonnull memo;
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic) double amount;
@property (nonatomic, copy) NSString * _Nonnull symbol;
@property (nonatomic) NSInteger decimal;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end







#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__x86_64__) && __x86_64__

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import Mykeycore;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MYKEYWalletLib",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC14MYKEYWalletLib19BaseProtocolRequest")
@interface BaseProtocolRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull appKey;
@property (nonatomic, copy) NSString * _Nonnull protocol;
@property (nonatomic, copy) NSString * _Nonnull version;
@property (nonatomic, copy) NSString * _Nonnull dappName;
@property (nonatomic, copy) NSString * _Nonnull dappIcon;
@property (nonatomic, copy) NSString * _Nonnull action;
@property (nonatomic, copy) NSString * _Nonnull uuID;
@property (nonatomic, copy) NSString * _Nonnull callback;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib24AuthorizeProtocolRequest")
@interface AuthorizeProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSString * _Nonnull loginUrl;
@property (nonatomic, copy) NSString * _Nonnull loginMemo;
@property (nonatomic, copy) NSString * _Nonnull dappUserName;
@property (nonatomic, copy) NSString * _Nonnull requestPubKey;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11BaseRequest")
@interface BaseRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull callbackUrl;
@property (nonatomic, copy) NSString * _Nonnull info;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib16AuthorizeRequest")
@interface AuthorizeRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull userName;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib10BaseAction")
@interface BaseAction : NSObject
@property (nonatomic, copy) NSString * _Nonnull info;
@property (nonatomic, copy) NSString * _Nonnull account;
@property (nonatomic, copy) NSString * _Nonnull name;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15BaseJniResponse")
@interface BaseJniResponse : NSObject
@property (nonatomic) NSInteger result_code;
@property (nonatomic, copy) NSString * _Nonnull result_message;
@property (nonatomic) id _Nullable result_data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC14MYKEYWalletLib14ContractAction")
@interface ContractAction : BaseAction
/// JSONString
@property (nonatomic, copy) NSString * _Nonnull data;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib23ContractProtocolRequest")
@interface ContractProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSArray<BaseAction *> * _Nonnull actions;
@property (nonatomic, copy) NSString * _Nonnull desc;
@property (nonatomic, copy) NSString * _Nonnull contractUrl;
@property (nonatomic, copy) NSString * _Nonnull orderId;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15ContractRequest")
@interface ContractRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic, copy) NSArray<BaseAction *> * _Nonnull actions;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib13EmptyResponse")
@interface EmptyResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib19EncodeParamResponse")
@interface EncodeParamResponse : NSObject
@property (nonatomic, copy) NSString * _Nonnull encode_data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ErrorCode, closed) {
    /// 0
    ErrorCodeCancel = 0,
    /// 1
    ErrorCodeSuccess = 1,
    /// 2
    ErrorCodeFailure = 2,
    /// 10001
    ErrorCodeCannotWakeUp = 10001,
    /// 10002
    ErrorCodeNotInstall = 10002,
    /// 10003
    ErrorCodeFreezed = 10003,
    /// 10004
    ErrorCodeUninitialized = 10004,
    /// 10005
    ErrorCodeTimeOut = 10005,
    /// 10006
    ErrorCodeDuplicateBound = 10006,
    /// 10007
    ErrorCodeUnbound = 10007,
    /// 10008
    ErrorCodeDappBounded = 10008,
    /// 10009
    ErrorCodeMYKEYBounded = 10009,
    /// 10010
    ErrorCodeBoundInfoMismatch = 10010,
    /// 10011
    ErrorCodeMYKEYAccountNotExist = 10011,
    /// 10012
    ErrorCodeIllegalParameter = 10012,
    /// 10013
    ErrorCodeInsufficientBalance = 10013,
};

@class InitRequest;
@class InitSimpleRequest;

SWIFT_CLASS("_TtC14MYKEYWalletLib10InitHandle")
@interface InitHandle : NSObject
/// Initialization needs to be performed on the main thread.
- (InitRequest * _Nonnull)handleWithInitRequest:(InitRequest * _Nonnull)initRequest SWIFT_WARN_UNUSED_RESULT;
- (InitRequest * _Nonnull)handleWithInitSimpleRequest:(InitSimpleRequest * _Nonnull)initSimpleRequest SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11InitRequest")
@interface InitRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull protocol;
@property (nonatomic, copy) NSString * _Nonnull appKey;
@property (nonatomic, copy) NSUUID * _Nullable UUID;
@property (nonatomic, copy) NSString * _Nonnull dappName;
@property (nonatomic, copy) NSString * _Nonnull dappIcon;
/// Default is ‘false’ , If MYKEY is not installed, go to the download page.
@property (nonatomic) BOOL disableInstall;
/// scheme
@property (nonatomic, copy) NSString * _Nonnull scheme;
/// Base url of MYKEY server,default is the distribution environment.
@property (nonatomic, copy) NSString * _Nonnull mykeyServer;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithInitSimpleRequest:(InitSimpleRequest * _Nonnull)initSimpleRequest OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib17InitSimpleRequest")
@interface InitSimpleRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull protocol;
@property (nonatomic, copy) NSString * _Nonnull dappName;
@property (nonatomic, copy) NSString * _Nonnull dappIcon;
/// Default is ‘false’ , If MYKEY is not installed, go to the download page.
@property (nonatomic) BOOL disableInstall;
/// scheme
@property (nonatomic, copy) NSString * _Nonnull scheme;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib19JniUserAgentRequest")
@interface JniUserAgentRequest : NSObject
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib16MYKEYApiResponse")
@interface MYKEYApiResponse : NSObject <MykeycoreApiRequestCallback>
- (nonnull instancetype)initWithSuccess:(void (^ _Nullable)(NSString * _Nonnull))success failure:(void (^ _Nullable)(NSString * _Nonnull))failure OBJC_DESIGNATED_INITIALIZER;
- (void)onSuccess:(NSString * _Null_unspecified)response;
- (void)onError:(NSInteger)errorCode errorMsg:(NSString * _Null_unspecified)errorMsg;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib13MYKEYResponse")
@interface MYKEYResponse : NSObject
@property (nonatomic, copy) void (^ _Nullable onSuccess)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onFailure)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onCancel)(void);
- (nonnull instancetype)initWithSuccess:(void (^ _Nullable)(NSString * _Nonnull))success failure:(void (^ _Nullable)(NSString * _Nonnull))failure cancelled:(void (^ _Nullable)(void))cancelled OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11MYKEYWallet")
@interface MYKEYWallet : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MYKEYWallet * _Nonnull shared;)
+ (MYKEYWallet * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull appKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull scheme;
@property (nonatomic, readonly, copy) NSString * _Nonnull uuid;
@property (nonatomic, readonly, copy) NSString * _Nonnull dappName;
@property (nonatomic, readonly, copy) NSString * _Nonnull dappIcon;
@property (nonatomic, readonly) BOOL disableInstall;
@property (nonatomic, readonly, copy) NSString * _Nonnull protocol;
@property (nonatomic, readonly, copy) NSString * _Nonnull mykeyServer;
@end


@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
/// Initialization needs to be performed on the main thread.
- (void)initWalletWithInitData:(InitRequest * _Nonnull)initData SWIFT_METHOD_FAMILY(none);
/// Initialization needs to be performed on the main thread.
- (void)initWalletSimpleWithInitSimpleData:(InitSimpleRequest * _Nonnull)initSimpleData SWIFT_METHOD_FAMILY(none);
@end


@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
- (void)getBalanceWithChain:(NSString * _Nonnull)chain code:(NSString * _Nonnull)code symbol:(NSString * _Nonnull)symbol completionHandler:(MYKEYApiResponse * _Nonnull)completionHandler;
- (void)getUnlockListWithChain:(NSString * _Nonnull)chain code:(NSString * _Nonnull)code symbol:(NSString * _Nonnull)symbol completionHandler:(MYKEYApiResponse * _Nonnull)completionHandler;
- (void)getBoundInfoWithCompletionHandler:(MYKEYApiResponse * _Nonnull)completionHandler;
@end


@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
/// Parse the callback data
- (void)handleUrlWithUrl:(NSURL * _Nonnull)url;
@end

@class TransferRequest;
@class SignRequest;

@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
- (void)authorizeWithAuthorizeRequest:(AuthorizeRequest * _Nonnull)authorizeRequest response:(MYKEYResponse * _Nonnull)response;
- (void)transferWithTransferRequest:(TransferRequest * _Nonnull)transferRequest response:(MYKEYResponse * _Nonnull)response;
- (void)contractWithContractRequest:(ContractRequest * _Nonnull)contractRequest response:(MYKEYResponse * _Nonnull)response;
- (void)signWithSignRequest:(SignRequest * _Nonnull)signRequest response:(MYKEYResponse * _Nonnull)response;
- (void)redirectToMYKEYWithSimpleWalletWithBaseRequest:(BaseProtocolRequest * _Nonnull)baseRequest response:(MYKEYResponse * _Nonnull)response;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15MYKEYWalletResp")
@interface MYKEYWalletResp : NSObject
@property (nonatomic, copy) NSString * _Nonnull action;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull data;
@property (nonatomic) NSInteger code;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib21RequestPubKeyResponse")
@interface RequestPubKeyResponse : NSObject
@property (nonatomic, copy) NSString * _Nonnull pub_key;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib19SignProtocolRequest")
@interface SignProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, copy) NSString * _Nonnull signUrl;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11SignRequest")
@interface SignRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TransferData;

SWIFT_CLASS("_TtC14MYKEYWalletLib14TransferAction")
@interface TransferAction : BaseAction
@property (nonatomic, strong) TransferData * _Nonnull data;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib12TransferData")
@interface TransferData : NSObject
@property (nonatomic, copy) NSString * _Nonnull from;
@property (nonatomic, copy) NSString * _Nonnull to;
@property (nonatomic, copy) NSString * _Nonnull quantity;
@property (nonatomic, copy) NSString * _Nonnull memo;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib23TransferProtocolRequest")
@interface TransferProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSString * _Nonnull from;
@property (nonatomic, copy) NSString * _Nonnull to;
@property (nonatomic) double amount;
@property (nonatomic, copy) NSString * _Nonnull contract;
@property (nonatomic, copy) NSString * _Nonnull symbol;
@property (nonatomic) NSInteger precision;
@property (nonatomic, copy) NSString * _Nonnull dappData;
@property (nonatomic, copy) NSString * _Nonnull desc;
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic, copy) NSString * _Nonnull transferUrl;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15TransferRequest")
@interface TransferRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull from;
@property (nonatomic, copy) NSString * _Nonnull to;
@property (nonatomic, copy) NSString * _Nonnull contractName;
@property (nonatomic, copy) NSString * _Nonnull memo;
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic) double amount;
@property (nonatomic, copy) NSString * _Nonnull symbol;
@property (nonatomic) NSInteger decimal;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end







#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import Mykeycore;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MYKEYWalletLib",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC14MYKEYWalletLib19BaseProtocolRequest")
@interface BaseProtocolRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull appKey;
@property (nonatomic, copy) NSString * _Nonnull protocol;
@property (nonatomic, copy) NSString * _Nonnull version;
@property (nonatomic, copy) NSString * _Nonnull dappName;
@property (nonatomic, copy) NSString * _Nonnull dappIcon;
@property (nonatomic, copy) NSString * _Nonnull action;
@property (nonatomic, copy) NSString * _Nonnull uuID;
@property (nonatomic, copy) NSString * _Nonnull callback;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib24AuthorizeProtocolRequest")
@interface AuthorizeProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSString * _Nonnull loginUrl;
@property (nonatomic, copy) NSString * _Nonnull loginMemo;
@property (nonatomic, copy) NSString * _Nonnull dappUserName;
@property (nonatomic, copy) NSString * _Nonnull requestPubKey;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11BaseRequest")
@interface BaseRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull callbackUrl;
@property (nonatomic, copy) NSString * _Nonnull info;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib16AuthorizeRequest")
@interface AuthorizeRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull userName;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib10BaseAction")
@interface BaseAction : NSObject
@property (nonatomic, copy) NSString * _Nonnull info;
@property (nonatomic, copy) NSString * _Nonnull account;
@property (nonatomic, copy) NSString * _Nonnull name;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15BaseJniResponse")
@interface BaseJniResponse : NSObject
@property (nonatomic) NSInteger result_code;
@property (nonatomic, copy) NSString * _Nonnull result_message;
@property (nonatomic) id _Nullable result_data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC14MYKEYWalletLib14ContractAction")
@interface ContractAction : BaseAction
/// JSONString
@property (nonatomic, copy) NSString * _Nonnull data;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib23ContractProtocolRequest")
@interface ContractProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSArray<BaseAction *> * _Nonnull actions;
@property (nonatomic, copy) NSString * _Nonnull desc;
@property (nonatomic, copy) NSString * _Nonnull contractUrl;
@property (nonatomic, copy) NSString * _Nonnull orderId;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15ContractRequest")
@interface ContractRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic, copy) NSArray<BaseAction *> * _Nonnull actions;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib13EmptyResponse")
@interface EmptyResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib19EncodeParamResponse")
@interface EncodeParamResponse : NSObject
@property (nonatomic, copy) NSString * _Nonnull encode_data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ErrorCode, closed) {
    /// 0
    ErrorCodeCancel = 0,
    /// 1
    ErrorCodeSuccess = 1,
    /// 2
    ErrorCodeFailure = 2,
    /// 10001
    ErrorCodeCannotWakeUp = 10001,
    /// 10002
    ErrorCodeNotInstall = 10002,
    /// 10003
    ErrorCodeFreezed = 10003,
    /// 10004
    ErrorCodeUninitialized = 10004,
    /// 10005
    ErrorCodeTimeOut = 10005,
    /// 10006
    ErrorCodeDuplicateBound = 10006,
    /// 10007
    ErrorCodeUnbound = 10007,
    /// 10008
    ErrorCodeDappBounded = 10008,
    /// 10009
    ErrorCodeMYKEYBounded = 10009,
    /// 10010
    ErrorCodeBoundInfoMismatch = 10010,
    /// 10011
    ErrorCodeMYKEYAccountNotExist = 10011,
    /// 10012
    ErrorCodeIllegalParameter = 10012,
    /// 10013
    ErrorCodeInsufficientBalance = 10013,
};

@class InitRequest;
@class InitSimpleRequest;

SWIFT_CLASS("_TtC14MYKEYWalletLib10InitHandle")
@interface InitHandle : NSObject
/// Initialization needs to be performed on the main thread.
- (InitRequest * _Nonnull)handleWithInitRequest:(InitRequest * _Nonnull)initRequest SWIFT_WARN_UNUSED_RESULT;
- (InitRequest * _Nonnull)handleWithInitSimpleRequest:(InitSimpleRequest * _Nonnull)initSimpleRequest SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11InitRequest")
@interface InitRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull protocol;
@property (nonatomic, copy) NSString * _Nonnull appKey;
@property (nonatomic, copy) NSUUID * _Nullable UUID;
@property (nonatomic, copy) NSString * _Nonnull dappName;
@property (nonatomic, copy) NSString * _Nonnull dappIcon;
/// Default is ‘false’ , If MYKEY is not installed, go to the download page.
@property (nonatomic) BOOL disableInstall;
/// scheme
@property (nonatomic, copy) NSString * _Nonnull scheme;
/// Base url of MYKEY server,default is the distribution environment.
@property (nonatomic, copy) NSString * _Nonnull mykeyServer;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithInitSimpleRequest:(InitSimpleRequest * _Nonnull)initSimpleRequest OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib17InitSimpleRequest")
@interface InitSimpleRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull protocol;
@property (nonatomic, copy) NSString * _Nonnull dappName;
@property (nonatomic, copy) NSString * _Nonnull dappIcon;
/// Default is ‘false’ , If MYKEY is not installed, go to the download page.
@property (nonatomic) BOOL disableInstall;
/// scheme
@property (nonatomic, copy) NSString * _Nonnull scheme;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib19JniUserAgentRequest")
@interface JniUserAgentRequest : NSObject
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib16MYKEYApiResponse")
@interface MYKEYApiResponse : NSObject <MykeycoreApiRequestCallback>
- (nonnull instancetype)initWithSuccess:(void (^ _Nullable)(NSString * _Nonnull))success failure:(void (^ _Nullable)(NSString * _Nonnull))failure OBJC_DESIGNATED_INITIALIZER;
- (void)onSuccess:(NSString * _Null_unspecified)response;
- (void)onError:(NSInteger)errorCode errorMsg:(NSString * _Null_unspecified)errorMsg;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib13MYKEYResponse")
@interface MYKEYResponse : NSObject
@property (nonatomic, copy) void (^ _Nullable onSuccess)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onFailure)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onCancel)(void);
- (nonnull instancetype)initWithSuccess:(void (^ _Nullable)(NSString * _Nonnull))success failure:(void (^ _Nullable)(NSString * _Nonnull))failure cancelled:(void (^ _Nullable)(void))cancelled OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11MYKEYWallet")
@interface MYKEYWallet : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MYKEYWallet * _Nonnull shared;)
+ (MYKEYWallet * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull appKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull scheme;
@property (nonatomic, readonly, copy) NSString * _Nonnull uuid;
@property (nonatomic, readonly, copy) NSString * _Nonnull dappName;
@property (nonatomic, readonly, copy) NSString * _Nonnull dappIcon;
@property (nonatomic, readonly) BOOL disableInstall;
@property (nonatomic, readonly, copy) NSString * _Nonnull protocol;
@property (nonatomic, readonly, copy) NSString * _Nonnull mykeyServer;
@end


@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
/// Initialization needs to be performed on the main thread.
- (void)initWalletWithInitData:(InitRequest * _Nonnull)initData SWIFT_METHOD_FAMILY(none);
/// Initialization needs to be performed on the main thread.
- (void)initWalletSimpleWithInitSimpleData:(InitSimpleRequest * _Nonnull)initSimpleData SWIFT_METHOD_FAMILY(none);
@end


@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
- (void)getBalanceWithChain:(NSString * _Nonnull)chain code:(NSString * _Nonnull)code symbol:(NSString * _Nonnull)symbol completionHandler:(MYKEYApiResponse * _Nonnull)completionHandler;
- (void)getUnlockListWithChain:(NSString * _Nonnull)chain code:(NSString * _Nonnull)code symbol:(NSString * _Nonnull)symbol completionHandler:(MYKEYApiResponse * _Nonnull)completionHandler;
- (void)getBoundInfoWithCompletionHandler:(MYKEYApiResponse * _Nonnull)completionHandler;
@end


@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
/// Parse the callback data
- (void)handleUrlWithUrl:(NSURL * _Nonnull)url;
@end

@class TransferRequest;
@class SignRequest;

@interface MYKEYWallet (SWIFT_EXTENSION(MYKEYWalletLib))
- (void)authorizeWithAuthorizeRequest:(AuthorizeRequest * _Nonnull)authorizeRequest response:(MYKEYResponse * _Nonnull)response;
- (void)transferWithTransferRequest:(TransferRequest * _Nonnull)transferRequest response:(MYKEYResponse * _Nonnull)response;
- (void)contractWithContractRequest:(ContractRequest * _Nonnull)contractRequest response:(MYKEYResponse * _Nonnull)response;
- (void)signWithSignRequest:(SignRequest * _Nonnull)signRequest response:(MYKEYResponse * _Nonnull)response;
- (void)redirectToMYKEYWithSimpleWalletWithBaseRequest:(BaseProtocolRequest * _Nonnull)baseRequest response:(MYKEYResponse * _Nonnull)response;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15MYKEYWalletResp")
@interface MYKEYWalletResp : NSObject
@property (nonatomic, copy) NSString * _Nonnull action;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull data;
@property (nonatomic) NSInteger code;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib21RequestPubKeyResponse")
@interface RequestPubKeyResponse : NSObject
@property (nonatomic, copy) NSString * _Nonnull pub_key;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib19SignProtocolRequest")
@interface SignProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, copy) NSString * _Nonnull signUrl;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib11SignRequest")
@interface SignRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TransferData;

SWIFT_CLASS("_TtC14MYKEYWalletLib14TransferAction")
@interface TransferAction : BaseAction
@property (nonatomic, strong) TransferData * _Nonnull data;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib12TransferData")
@interface TransferData : NSObject
@property (nonatomic, copy) NSString * _Nonnull from;
@property (nonatomic, copy) NSString * _Nonnull to;
@property (nonatomic, copy) NSString * _Nonnull quantity;
@property (nonatomic, copy) NSString * _Nonnull memo;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib23TransferProtocolRequest")
@interface TransferProtocolRequest : BaseProtocolRequest
@property (nonatomic, copy) NSString * _Nonnull from;
@property (nonatomic, copy) NSString * _Nonnull to;
@property (nonatomic) double amount;
@property (nonatomic, copy) NSString * _Nonnull contract;
@property (nonatomic, copy) NSString * _Nonnull symbol;
@property (nonatomic) NSInteger precision;
@property (nonatomic, copy) NSString * _Nonnull dappData;
@property (nonatomic, copy) NSString * _Nonnull desc;
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic, copy) NSString * _Nonnull transferUrl;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MYKEYWalletLib15TransferRequest")
@interface TransferRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nonnull from;
@property (nonatomic, copy) NSString * _Nonnull to;
@property (nonatomic, copy) NSString * _Nonnull contractName;
@property (nonatomic, copy) NSString * _Nonnull memo;
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic) double amount;
@property (nonatomic, copy) NSString * _Nonnull symbol;
@property (nonatomic) NSInteger decimal;
@property (nonatomic, readonly, copy) NSString * _Nonnull action;
- (NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end







#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
