// Objective-C API for talking to mykeysdk Go package.
//   gobind -lang=objc mykeysdk
//
// File is generated by gobind. Do not edit.

#ifndef __Mykeycore_H__
#define __Mykeycore_H__

@import Foundation;
#include "Universe.objc.h"


@class MykeycoreInitEntity;
@protocol MykeycoreApiRequestCallback;
@class MykeycoreApiRequestCallback;

@protocol MykeycoreApiRequestCallback <NSObject>
- (void)onError:(long)errorCode errorMsg:(NSString*)errorMsg;
- (void)onSuccess:(NSString*)response;
@end

@interface MykeycoreInitEntity : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)appKey;
- (void)setAppKey:(NSString*)v;
- (NSString*)userId;
- (void)setUserId:(NSString*)v;
- (NSString*)baseUrl;
- (void)setBaseUrl:(NSString*)v;
- (NSString*)userAgent;
- (void)setUserAgent:(NSString*)v;
- (NSString*)device;
- (void)setDevice:(NSString*)v;
- (NSString*)sdkVersion;
- (void)setSdkVersion:(NSString*)v;
- (NSString*)uuid;
- (void)setUuid:(NSString*)v;
- (NSString*)deviceMode;
- (void)setDeviceMode:(NSString*)v;
- (NSString*)deviceOs;
- (void)setDeviceOs:(NSString*)v;
@end

/**
 * 产生一组公私钥
 */
FOUNDATION_EXPORT NSString* MykeycoreCreatePrivate(NSString* keystorePath);

/**
 * 数据加密
 */
FOUNDATION_EXPORT NSString* MykeycoreEncodeParam(NSString* param);

FOUNDATION_EXPORT NSString* MykeycoreGetBalance(NSString* chain, NSString* code, NSString* symbol, id<MykeycoreApiRequestCallback> requestCallBack);

FOUNDATION_EXPORT NSString* MykeycoreGetBindInfo(id<MykeycoreApiRequestCallback> requestCallBack);

FOUNDATION_EXPORT NSString* MykeycoreGetUnlockList(NSString* chain, NSString* code, NSString* symbol, id<MykeycoreApiRequestCallback> requestCallBack);

/**
 * 初始化调用,必须调用，否则其他接口会出问题
 */
FOUNDATION_EXPORT NSString* MykeycoreInit(MykeycoreInitEntity* initEntity);

/**
 * 获取SDK请求数据签名需要用的到私钥对应的公钥
 */
FOUNDATION_EXPORT NSString* MykeycoreRequestPubKey(void);

FOUNDATION_EXPORT NSString* MykeycoreSign(NSString* encryptPrivate, NSString* unsignedData);

FOUNDATION_EXPORT NSString* MykeycoreVerifySign(NSString* publicKey, NSString* signedData, NSString* unsignedData);

@class MykeycoreApiRequestCallback;

@interface MykeycoreApiRequestCallback : NSObject <goSeqRefInterface, MykeycoreApiRequestCallback> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onError:(long)errorCode errorMsg:(NSString*)errorMsg;
- (void)onSuccess:(NSString*)response;
@end

#endif
